version: "3"
services:
  ludwig:
    container_name: ludwig
    image: ludwig:1.0
    build:
      context: ./docker
      dockerfile: ./ludwig/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''