version: "3"
services:
  mljar-supervised:
    container_name: mljar-supervised
    image: mljar-supervised:1.0
    build:
      context: ./docker
      dockerfile: ./mljar-supervised/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''