version: "3"
services:
  pycaret:
    container_name: pycaret
    image: pycaret:1.0
    build:
      context: ./docker
      dockerfile: ./pycaret/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''