version: "3"
services:
  auto-sklearn:
    container_name: auto-sklearn
    image: auto-sklearn:1.0
    build:
      context: ./docker
      dockerfile: ./auto-sklearn/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''